#!/usr/bin/env bash
#
# ---------------------------------------------------------------------------
# Run the production configuration WITHOUT docker, to check it before the
# deployment on the server.
#
# The script starts a real PHP web server (or the sandbox runtime when PHP is
# not installed) that serves the repository with the production PHP settings,
# reads the configuration from an ".env" file and answers on
# http://127.0.0.1:${APP_HTTP_PORT} - exactly like nginx does inside the stack.
#
# It is a development helper, it must NOT be used as the production web server:
# nginx with deploy/nginx/default.conf remains the only supported front end.
#
# Usage:
#
#   bash scripts/demo-prod-stack.sh                # uses a temporary sqlite database
#   bash scripts/demo-prod-stack.sh --port 8090
#   bash scripts/demo-prod-stack.sh --check-only   # run the smoke test and exit (CI friendly)
#   bash scripts/demo-prod-stack.sh --keep         # keep the temporary config files
#
# What it verifies:
#
#   1. config-loader.php can read a ".env" file and defines the Config class,
#   2. the application boots with APP_ENV=production (no debug output),
#   3. /index.php/health answers with a healthy state,
#   4. the blocking of /storage, /application, /docs, /dev, /tests, /config.php
#      by the web server (the sandbox server implements the same rules as
#      deploy/nginx/default.conf, see dev/sandbox/server.mjs).
#
# Fork addition - not part of the upstream project (see CUSTOMIZATIONS.md).
# ---------------------------------------------------------------------------
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_PATH="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$APP_PATH"

PORT=8090
KEEP=0
CHECK_ONLY=0
HOST=127.0.0.1

while [ "$#" -gt 0 ]; do
    case "$1" in
        --port)
            shift
            PORT="${1:-8090}"
            ;;
        --keep) KEEP=1 ;;
        --check-only) CHECK_ONLY=1 ;;
        --host)
            shift
            HOST="${1:-127.0.0.1}"
            ;;
        -h|--help)
            sed -n '2,32p' "$0"
            exit 0
            ;;
        *) echo "Unknown argument: $1" >&2; exit 2 ;;
    esac

    shift
done

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m ok\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# 1. Temporary .env and config.php (the real ones are never overwritten)
# ---------------------------------------------------------------------------

ENV_FILE="$APP_PATH/.env"
CONFIG_FILE="$APP_PATH/config.php"
CONFIG_BACKUP=""
ENV_BACKUP=""

cleanup() {
    if [ "$KEEP" = '1' ]; then
        warn "Keeping $ENV_FILE (and the config.php of the demo run)."
        return
    fi

    # Remove the generated .env and bring the original files back.
    rm -f "$ENV_FILE"

    if [ -n "$ENV_BACKUP" ] && [ -f "$ENV_BACKUP" ]; then
        mv -f "$ENV_BACKUP" "$ENV_FILE"
    fi

    if [ -n "$CONFIG_BACKUP" ] && [ -f "$CONFIG_BACKUP" ]; then
        mv -f "$CONFIG_BACKUP" "$CONFIG_FILE"
    fi
}

trap cleanup EXIT

# A stopped script must not leave the ".env" or the "config.php" of the demo in place.
trap 'exit 130' INT TERM

if [ -f "$CONFIG_FILE" ]; then
    CONFIG_BACKUP="$CONFIG_FILE.demo-backup-$$"
    cp -a "$CONFIG_FILE" "$CONFIG_BACKUP"
    log "The existing config.php was saved to $CONFIG_BACKUP."
fi

# The sandbox and the local development environment run on sqlite, which the
# application only uses in the "development" environment (see
# application/config/development/database.php). The production installation runs
# on MySQL with APP_ENV=production.
if [ -f "$APP_PATH/storage/easyappointments.sqlite" ]; then
    ENV_MODE='development'
    DB_HOST='localhost'

    log 'A local sqlite database was found: the demo runs with APP_ENV=development.'
    warn 'This is the only difference to the production configuration (which uses MySQL).'
else
    ENV_MODE='production'
    DB_HOST='127.0.0.1'
fi

# The loader always reads ".env", so an existing file is moved aside before the
# generated one is written and restored by the EXIT trap.
if [ -f "$ENV_FILE" ]; then
    ENV_BACKUP="$ENV_FILE.demo-backup-$$"
    mv -f "$ENV_FILE" "$ENV_BACKUP"
    ok 'The existing .env was moved aside.'
fi

cat > "$ENV_FILE" <<ENV
# Generated by scripts/demo-prod-stack.sh - do not commit.
APP_ENV=${ENV_MODE}
APP_URL=http://${HOST}:${PORT}
APP_LANGUAGE=persian
DEBUG_MODE=false
ENCRYPTION_KEY=demo-only-key-not-for-production-0123456789abcdef

DB_HOST=${DB_HOST}
DB_NAME=easyappointments
DB_USERNAME=
DB_PASSWORD=demo-not-a-real-password

SMS_DRIVER=mock
ENV

printf '%s\n' '<?php require_once __DIR__ . "/config-loader.php";' > "$CONFIG_FILE"

ok "The application is configured from the environment (APP_ENV=${ENV_MODE})."

# ---------------------------------------------------------------------------
# 2. Loader check
# ---------------------------------------------------------------------------

if command -v php >/dev/null 2>&1; then
    log 'Checking config-loader.php with the local PHP ...'

    php -r '
        require "config-loader.php";
        echo "   base_url : " . Config::BASE_URL . PHP_EOL;
        echo "   language : " . Config::LANGUAGE . PHP_EOL;
        echo "   debug    : " . var_export(Config::DEBUG_MODE, true) . PHP_EOL;
        echo "   db host  : " . Config::DB_HOST . PHP_EOL;
        echo "   db pass  : " . (Config::DB_PASSWORD !== "" ? "set" : "EMPTY") . PHP_EOL;
        echo "   env(app) : " . var_export(getenv("APP_ENV"), true) . PHP_EOL;
    ' || die 'config-loader.php failed.'

    ok 'config-loader.php works.'
fi

# ---------------------------------------------------------------------------
# 3. Start a web server
# ---------------------------------------------------------------------------

log "Starting the demo server on http://${HOST}:${PORT} ..."

if command -v php >/dev/null 2>&1; then
    php -S "${HOST}:${PORT}" -t "$APP_PATH" &
    SERVER_PID=$!
else
    [ -f "$APP_PATH/dev/sandbox/server.mjs" ] || die 'Neither php nor dev/sandbox/server.mjs is available.'

    node "$APP_PATH/dev/sandbox/server.mjs" "$PORT" &
    SERVER_PID=$!
fi

trap 'kill "$SERVER_PID" 2>/dev/null || true; cleanup' EXIT

sleep 2

# ---------------------------------------------------------------------------
# 4. Smoke test
# ---------------------------------------------------------------------------

failures=0

check() {
    local description="$1"
    local url="$2"
    local expected="$3"

    local status
    status="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "$url" || echo '000')"

    if [ "$status" = "$expected" ]; then
        ok "$description (HTTP $status)"
    else
        warn "$description (HTTP $status, expected $expected)"
        failures=$((failures + 1))
    fi
}

log 'Running the smoke test ...'

check 'health endpoint answers'            "http://127.0.0.1:${PORT}/index.php/health" '200'
check 'storage directory is blocked'       "http://127.0.0.1:${PORT}/storage/easyappointments.sqlite" '404'
check 'application directory is blocked'   "http://127.0.0.1:${PORT}/application/config/config.php" '404'
check 'docs directory is blocked'          "http://127.0.0.1:${PORT}/docs/fa/step-01-production.md" '404'
check 'dev directory is blocked'           "http://127.0.0.1:${PORT}/dev/sandbox/setup.sh" '404'
check 'tests directory is blocked'         "http://127.0.0.1:${PORT}/tests/TestCase.php" '404'
check 'config.php is blocked'              "http://127.0.0.1:${PORT}/config.php" '404'
check 'the home page still works'          "http://127.0.0.1:${PORT}/index.php" '200'

if [ "$failures" -gt 0 ]; then
    warn "$failures check(s) failed."
else
    ok 'All checks passed.'
fi

log 'The health report:'
curl -s --max-time 10 "http://127.0.0.1:${PORT}/index.php/health" | sed 's/^/   /'
echo

if [ "$CHECK_ONLY" = '1' ]; then
    kill "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true

    if [ "$failures" -gt 0 ]; then
        die "$failures check(s) failed."
    fi

    ok 'The production configuration passed all checks.'
    exit 0
fi

log "The server is running on http://${HOST}:${PORT}. Press Ctrl+C to stop it."
wait "$SERVER_PID"
